language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn test --watchAll=false
  - yarn build
on:
  branch: master
deploy:
  provider: heroku
  api_key: 9f77b0fa-7b86-461c-9f2a-8f02e9e79669
  app: iim-a4-react-hello-world-jsouc
